// <auto-generated />
using CoderCarrer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoderCarrer.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230417194525_Banco")]
    partial class Banco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoderCarrer.Models.Vaga", b =>
                {
                    b.Property<int>("id_vaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vaga");

                    b.Property<string>("descricao_vaga")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_vaga");

                    b.Property<string>("empresa")
                        .HasColumnType("longtext")
                        .HasColumnName("empresa");

                    b.Property<string>("salario")
                        .HasColumnType("longtext")
                        .HasColumnName("salario");

                    b.Property<string>("titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.Property<string>("url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("id_vaga");

                    b.ToTable("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
